server:
  port: 8090

spring:
  application:
    name: gateway-service
    
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: exchange
        uri: lb://exchange
        predicates:
        - Path=/exchange/**
        filters:
        - RewritePath=/exchange/(?<path>.*), /$\{path}
      - id: conversion
        uri: lb://conversion
        predicates:
        - Path=/conversion/**
        filters:
        - RewritePath=/conversion/(?<path>.*), /$\{path}